Feature to add a comment
Abdessittir/JavaScript-capstone pull request #27
Opened 2022-11-23 10:56 UTC by yonas44

Hello @Abdessittir, so in this feature I implemented comment adding functionality, when you add a comment;
- When a user submits a comment through the form, it uses the involvement API to append a comment.

2022-11-23 13:34 UTC, Abdessittir requested changes
Hi @yonas44  great work 👍 , It was so close

# STATUS: CHANGES REQUIRED :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/199273222-010c4c63-4b9f-4149-9cac-ca9dde88e551.gif)

Here are some things you need to work on:

 - [ ] Take a look at the comment below
 - [ ] Kindly make sure that the comment show up un the screen when it gets added, because that is included in the project requirement
 
![req](https://user-images.githubusercontent.com/95412943/203559149-72bdffd6-dfa0-4632-bfd7-9db41aa360f0.PNG)

![commenttoDom](https://user-images.githubusercontent.com/95412943/203559170-c8b53169-79dc-42a8-a4c3-f785fb7a4585.PNG)

# OPTINAL:
Those are optional and you can skip them:

 - [ ] Kindly give the form elements some padding, so it look nice on the screen
 
![padding](https://user-images.githubusercontent.com/95412943/203559498-2da94f66-ad10-4a69-bcf9-2f0194a1d418.PNG)

## If you have any questions please feel free to ask 👍 

Happy coding 💯

2022-11-23 13:34 UTC, Abdessittir commented on src/api/addComment.js
> +    const res = await fetch(`${process.env.INVOLVMENT_URL}/apps/${process.env.APP_ID}`, {
Please make sure that the URL is correct

2022-11-23 19:05 UTC, yonas44 commented
Thank you @Abdessittir  for your feedback, I have added the changes please have a look at it and give me your feedback!

2022-11-24 07:23 UTC, Abdessittir approved these changes
Hi @yonas44 amazing work 💯, there is nothing to say other than it's time to merge your pull request.

# STATUS: APPROVED 🥇 

![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# Highlights 💪🏻

✅ Comment posted to the API correctly
✅ No linter errors
✅ Dom manipulated to add new comment 💯 

Happy Coding 👍

2022-11-24 07:33 UTC, merged